//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeMVCV1._2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBizeKesilenFatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBizeKesilenFatura()
        {
            this.TblBizeKesilenFaturaIcerik = new HashSet<TblBizeKesilenFaturaIcerik>();
        }
    
        public int BizeKesilenFaturaID { get; set; }
        public Nullable<long> VergiNo { get; set; }
        public string GelenFaturaUnvan { get; set; }
        public string GelenFaturaVergiDairesi { get; set; }
        public string GelenFaturaAdres { get; set; }
        public Nullable<int> GelenFaturaVergiNo { get; set; }
        public System.DateTime GelenFaturaTarih { get; set; }
    
        public virtual TblHesap TblHesap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBizeKesilenFaturaIcerik> TblBizeKesilenFaturaIcerik { get; set; }
    }
}
