//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeMVCV1._2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBizeKesilenFaturaIcerik
    {
        public int GelenFaturaNo { get; set; }
        public string GelenFaturaUrunAdi { get; set; }
        public Nullable<int> GelenFaturaUrunMiktar { get; set; }
        public Nullable<decimal> GelenFaturaBirimFiyat { get; set; }
        public Nullable<int> GelenFaturaKDVOrani { get; set; }
        public int GelenFaturaSatirNo { get; set; }
        public int GelenFaturaID { get; set; }
    
        public virtual TblBizeKesilenFatura TblBizeKesilenFatura { get; set; }
    }
}
