//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeMVCV1._2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKesilenFaturaIcerik
    {
        public int KesilanFaturaSatirNo { get; set; }
        public int GidenFaturaNo { get; set; }
        public string GidenFaturaUrunAdi { get; set; }
        public Nullable<int> GidenFaturaUrunMiktari { get; set; }
        public Nullable<decimal> GidenFaturaBirimFiyati { get; set; }
        public Nullable<int> GidenFaturaKDVOrani { get; set; }
        public int GidenFaturaID { get; set; }
    
        public virtual TblKesilenFatura TblKesilenFatura { get; set; }
    }
}
