//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeMVCV1._2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKesilenFatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKesilenFatura()
        {
            this.TblKesilenFaturaIcerik = new HashSet<TblKesilenFaturaIcerik>();
        }
    
        public int KesilenFaturaID { get; set; }
        public Nullable<long> VergiNo { get; set; }
        public string GidenFaturaUnvan { get; set; }
        public string GidenFaturaVergiDairesi { get; set; }
        public string GidenFaturaAdres { get; set; }
        public Nullable<long> GidenFaturaVergiNo { get; set; }
        public Nullable<System.DateTime> GidenFaturaTarih { get; set; }
    
        public virtual TblHesap TblHesap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKesilenFaturaIcerik> TblKesilenFaturaIcerik { get; set; }
    }
}
