//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeMVCV1._2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVarliklar
    {
        public int VarlikID { get; set; }
        public Nullable<long> KullaniciVergiNo { get; set; }
        public Nullable<decimal> Girdiler { get; set; }
        public Nullable<decimal> Ciktilar { get; set; }
    
        public virtual TblHesap TblHesap { get; set; }
    }
}
